snow app bundle
sfc-gh-cgorrie/snowcli pull request #4
Opened 2023-08-31 19:55 UTC by sfc-gh-cgorrie

TBD

2023-09-01 17:54 UTC, sfc-gh-cgorrie commented on src/snowcli/output/printing.py
> +        return self
Allows us to configure the exit value of `snowcli`.

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +class SrcDestPair:
Can we reuse `PathMapping` from https://github.com/sfc-gh-cgorrie/snowcli/blob/main/src/snowcli/cli/project/schema.py#L56  since that is also handling source/destination pairs?

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/manager.py
> +        # self.definition_manager = DefinitionManager(search_path)
Uncomment? We are using this in the property methods below.

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/manager.py
> +    def definition(self) -> dict:
nit: native_app_definition, specifically?

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +def build_bundle(project_root: Path, deploy_root: Path, artifacts: List[SrcDestPair]):
Not sure if this function should reside in `artifacts.py`. From a reader's perspective, all the above methods are utility functions on the artifact. But the bulk of bundle is handled by this function, which I see as a part of the native app manager itself.

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +    deploy_root = deploy_root.resolve()
Can we name this differently from the parameter `deploy_root` ? Ease of understanding if I don't necessarily remember this re-assignment.

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +            source_paths = [source_path]
`source_paths` is always a singleton list? Do we need a list in that case?

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +        if specifies_directory(artifact.dest):
Will Path.is_dir() help here instead of defining our own function?

2023-09-05 21:25 UTC, sfc-gh-bgoel commented on src/snowcli/output/printing.py
> +        return self
Love this! I'll also see where I can re-use this in my init command. 

Suggestion: can we also allow a `exit_message` string? I read that if you specify a string in system exit instead of an int, it is also understood as a non-zero error, and is helpful for the person debugging.

2023-09-05 23:48 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/artifacts.py
> +class SrcDestPair:
Unfortunately not, for two reasons:

1. The JSON type that `PathMapping` uses is concrete object, not a class, so it can't be used in the same ways as a dataclass and we won't get typing, and
2. `PathMapping` needs to accept the possibilities that `dest` might not be present and that `src` might be a glob pattern.

This way aligns with our discussion that we'll keep the config "as-is" and then parse it into higher-level data structures.

2023-09-05 23:48 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/manager.py
> +    def definition(self) -> dict:
I disagree because it's called the native app manager, so `native_app_manager.native_app_definition` feels unnecessarily repetitive.

2023-09-05 23:50 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/artifacts.py
> +            source_paths = [source_path]
In the other if statement, it can be multiple files (all those that the glob resolves to).

2023-09-05 23:51 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/artifacts.py
> +        if specifies_directory(artifact.dest):
No, because the directory will not exist the first time we build the bundle. As per the spec, a trailing slash indicates that we are trying to copy artifacts _into_ a folder, rather than renaming the source file _as_ the destination path's basename.

2023-09-05 23:55 UTC, sfc-gh-cgorrie commented on src/snowcli/output/printing.py
> +        return self
We're calling `typer.Exit()` instead of exiting ourselves, so we don't have the ability to re-use `sys.exit(...)`'s behaviour. However I like the thought, and I think we could rename this something like `fatal_error`, e.g.

```python
try:
    # command code
except Exception as e:
    return OutputData.fatal_error(e, code=2)
```

Where `code` was optional and defaults to 1, perhaps.

2023-09-05 23:56 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/manager.py
> +        # self.definition_manager = DefinitionManager(search_path)
Yep, will do as soon as #1 is merged.

2023-09-05 23:58 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/artifacts.py
> +def build_bundle(project_root: Path, deploy_root: Path, artifacts: List[SrcDestPair]):
I agree with you to a point, but from a python code style perspective I'm not really a fan of too much OOP here. Having it as a method makes it easier to test and lets the reader know it will not mutate any state inside of the Native App Manager.

There are definitely pros and cons to both approaches, happy to discuss further.

2023-09-06 00:29 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/commands.py
> +@catch_error(ArtifactError, exit_code=1)
@sfc-gh-bgoel I thought a bit more about it and I think this might be the cleanest way forward for error handling, would love your thoughts.

2023-09-06 01:11 UTC, sfc-gh-bgoel approved these changes
LGTM, just need to uncomment the definition manager property once the other PR is merged.

2023-09-06 01:11 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +def build_bundle(project_root: Path, deploy_root: Path, artifacts: List[SrcDestPair]):
I also take your point, I prefer things very OOP over any other paradigm for sure. 
My concern here is: we do not want separate code organization coming in from different contributors, i.e. Naeem, yourself and me. For example, the code I wrote for init is written imo, with an OOP perspective. We should probably align on a unified organization (This can be done as a special refactor PR).

2023-09-06 01:11 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/artifacts.py
> +            source_paths = [source_path]
Aah thanks for pointing that out, I overlooked the context while writing that!

2023-09-06 01:11 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/manager.py
> +    def definition(self) -> dict:
Fair enough!

2023-09-06 01:11 UTC, sfc-gh-bgoel commented on src/snowcli/cli/nativeapp/commands.py
> +@catch_error(ArtifactError, exit_code=1)
🚀
I'll refactor code from my merged PRs with this.

2023-09-06 01:12 UTC, sfc-gh-bgoel requested changes
Sorry, I see that the unit-tests are failing due to NativeAppManager's instantiation change.

2023-09-06 14:17 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/nativeapp/artifacts.py
> +def build_bundle(project_root: Path, deploy_root: Path, artifacts: List[SrcDestPair]):
Yes, I agree, we should remain consistent. I just looked and don't see an internal style guide here for Python. I suppose we'll have to work towards something we agree on as a team!

2023-09-06 15:00 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/project/definition_manager.py
> +            )
@sfc-gh-nkhalid moved this so that we can always initialize the definition manager.

This also will let us check in `init` to see if project definition exists and fail out.

2023-09-06 15:17 UTC, sfc-gh-cgorrie commented on src/snowcli/cli/project/definition_manager.py
> +                return self._project_config_paths
@sfc-gh-nkhalid you may want to pull these changes into the upstream PR. Before it was actually incorrect, we would set `_project_config_paths` to `None`, and also we would never return a user config.

2023-09-06 16:52 UTC, sfc-gh-bgoel approved these changes
LGTM 🚀

2023-09-06 16:58 UTC, merged